from __future__ import annotations

import os
from pathlib import Path
from typing import Optional, Dict, Any

from .val_semantic import evaluate_yolo_semantic


def train_yolo(
    model: str = "yolov8n-seg.pt",
    data: str | Path = "data.yaml",
    epochs: int = 50,
    imgsz: int = 2048,
    batch: int = 1,
    lr0: float = 1e-4,
    device: str = "cuda",
    workers: int = 4,
    amp: bool = True,
    augment: bool = True,
    project: str = "checkpoints/yolo_benchmark",
    name: str = "exp",
    eval_semantic: bool = True,
    **kwargs: Any,
) -> Dict[str, Any]:
    """
    Train an Ultralytics YOLO segmentation model for paper benchmarking against SOAR.

    Args:
        model: Model architecture or pretrained checkpoint (e.g. 'yolov8n-seg.pt', 'yolo11n-seg.pt').
        data: Path to dataset data.yaml generated by yolo.converter.
        epochs: Training epochs.
        imgsz: Native image resolution (e.g. 2048, 1024, 512).
        batch: Physical batch size.
        lr0: Initial learning rate.
        device: CUDA device ID or 'cuda'/'cpu'.
        workers: DataLoader workers.
        amp: Enable Automatic Mixed Precision (AMP).
        augment: If False, disables all augmentations for fair baseline comparison with SOAR --no-augment.
        project: Directory to store training artifacts and weights.
        name: Name of the experiment.
        eval_semantic: If True, evaluates the best checkpoint on dense semantic metrics (mIoU, clDice, bIoU).

    Returns:
        Dictionary of results and evaluated metrics.
    """
    try:
        from ultralytics import YOLO
    except ImportError:
        raise ImportError(
            "ultralytics is required for training YOLO models. Install it via: pip install ultralytics"
        )

    data_path = Path(data).resolve()
    if not data_path.is_file():
        raise FileNotFoundError(f"data.yaml not found at: {data_path}")

    # Build YOLO training hyperparameters
    train_args: Dict[str, Any] = {
        "data": str(data_path),
        "epochs": epochs,
        "imgsz": imgsz,
        "batch": batch,
        "lr0": lr0,
        "device": device,
        "workers": workers,
        "amp": amp,
        "project": project,
        "name": name,
        "exist_ok": True,
        "plots": True,
        "save": True,
    }

    if not augment:
        print("[YOLO Training] Data augmentation disabled (--no-augment mode).")
        train_args.update({
            "mosaic": 0.0,
            "mixup": 0.0,
            "fliplr": 0.0,
            "flipud": 0.0,
            "degrees": 0.0,
            "translate": 0.0,
            "scale": 0.0,
            "shear": 0.0,
            "perspective": 0.0,
            "hsv_h": 0.0,
            "hsv_s": 0.0,
            "hsv_v": 0.0,
            "erasing": 0.0,
            "crop_fraction": 1.0,
        })

    # Allow custom overrides
    train_args.update(kwargs)

    print(f"\n{'='*70}")
    print(f"Starting YOLO Segmentation Training")
    print(f"  - Model:         {model}")
    print(f"  - Data YAML:     {data_path}")
    print(f"  - Resolution:    {imgsz}x{imgsz}")
    print(f"  - Epochs:        {epochs}")
    print(f"  - Batch Size:    {batch}")
    print(f"  - Learning Rate: {lr0}")
    print(f"  - Augmentation:  {'Enabled' if augment else 'Disabled'}")
    print(f"  - Output Dir:    {project}/{name}")
    print(f"{'='*70}\n")

    yolo_model = YOLO(model)
    results = yolo_model.train(**train_args)

    best_weights = Path(project) / name / "weights" / "best.pt"
    if not best_weights.is_file():
        best_weights = Path(project) / name / "weights" / "last.pt"

    eval_results = {}
    if eval_semantic and best_weights.is_file():
        print(f"\n[YOLO Training] Training complete! Running semantic benchmark on {best_weights}...")
        vis_dir = Path(project) / name / "semantic_visualizations"
        eval_results = evaluate_yolo_semantic(
            weights_path=best_weights,
            data_yaml_path=data_path,
            img_size=imgsz,
            device=device,
            save_dir=vis_dir,
            num_vis_samples=4,
        )

    return {
        "train_results": results,
        "best_weights": str(best_weights),
        "semantic_metrics": eval_results,
    }
